import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import { useRecoilState, useRecoilValue } from "recoil";
import { userState } from "../components/store/Auth/auth";

import { textState } from "../components/store/Auth/editor";

import React, { useState, useEffect, useRef } from "react";

import Editor from "@monaco-editor/react";

import Grid from "@mui/material/Grid";
import Button from "@mui/material/Button";
import Box from "@mui/material/Box";

export default function Home() {
  useEffect(() => {
    (async () => {
      // apiなどからユーザー情報を取得して、setUserでグローバルstateを更新する
    })();
  }, []);

  //
  const EditordefaultValue = `def main():
    print('Hello World !!')

if __name__ == '__main__':
    main()`;

  //
  const ToPlayBtn = () => {
    return (
      <div
        style={{
          textAlign: "center",
          marginTop: "40px",
          marginBottom: "60px",
        }}
      >
        <Button href="/play" variant="contained" disableElevation size="large">
          試してみる ▶
        </Button>
      </div>
    );
  };

  const editorRefIn = useRef(null);
  function handleEditorDidMountIn(editor, monaco) {
    editorRefIn.current = editor;
  }
  function submit() {
    window.alert(editorRefIn.current.getValue());
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Grid container spacing={2} style={{ padding: "0 2em" }}>
        <Grid item xs={6}>
          <h1>プログラムを実行しよう !! 🏃🏻</h1>
          <h3>ユーザー登録なしでPythonを実行できます。</h3>
          <Box
            sx={{ bgcolor: "info.light", color: "error.contrastText", p: 2 }}
          >
            <h3>ユーザー登録すると...</h3>
            <ul>
              <li>書いたコードを共有・保存できます</li>
            </ul>
          </Box>
          <Box
            sx={{ bgcolor: "error.light", color: "error.contrastText", p: 2 }}
          >
            <h5>
              仕様が変更になることがあります。また、データが消えることがあります。
            </h5>
          </Box>

          <h3
            style={{
              textAlign: "center",
              marginTop: "30px",
              marginBottom: "30px",
            }}
          >
            実行できる言語
          </h3>
          <Grid container spacing={2} style={{ padding: "0 3em" }}></Grid>
          <ToPlayBtn />
        </Grid>
        <Grid item xs={6}>
          <Button onClick={submit}>内容</Button>
          <Editor
            height="40vh"
            theme="vs-dark"
            language="python"
            //defaultValue={EditordefaultValue}
            onChange={handleEditorDidMountIn}
            //onMount={handleEditorDidMountIn}
            //options={{ readOnly: "true" }}
          />
          <div
            style={{
              backgroundColor: "#1E1E1E",
              minHeight: "130px",
              padding: "10px",
              position: "relative",
            }}
          >
            <code
              id="outPut"
              style={{
                whiteSpace: "pre-wrap",
                color: "white",
                overflowWrap: "break-word",
              }}
            >
              $ python main.py <br />
              Hello World !!
            </code>
          </div>
          <ToPlayBtn />
        </Grid>
      </Grid>
    </>
  );
}
