import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import { useRecoilState, useRecoilValue } from "recoil";
import { userState } from "../components/store/Auth/auth";

import { textState } from "../components/store/Auth/editor";

import React, { useState, useEffect } from "react";

import Editor from "@monaco-editor/react";

export default function Home() {
  const [user, setUser] = useRecoilState(userState);
  // useRecoilValueで値だけ宣言することも可能
  const userValue = useRecoilValue(userState);

  useEffect(() => {
    (async () => {
      // apiなどからユーザー情報を取得して、setUserでグローバルstateを更新する
      setUser({ id: null, name: "babab", email: "a@test.com" });
      console.log(userValue);
    })();
  }, []);

  const [text, setText] = useRecoilState(textState);

  const [mdCode, setMdCode] = useState("");
  function handleMdEditorChange(value) {
    setMdCode(value);
  }

  //
  const EditordefaultValue = `def main():
    print('Hello World !!')

if __name__ == '__main__':
    main()`;

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p>{JSON.stringify(userValue)}</p>
      <hr />
      <p>{JSON.stringify(user)}</p>
      <hr />
      <code>{text}</code>
      <hr />

      <Editor
        height="100vh"
        theme="vs-dark"
        language="python"
        // defaultValue={EditordefaultValue}
        // value={text}
        onChange={handleMdEditorChange}
        //onChange={onChange}
      />
      {/* <input type="text" value={text} onChange={onChange} /> */}
      <div
        style={{
          backgroundColor: "#1E1E1E",
          minHeight: "130px",
          padding: "10px",
          position: "relative",
        }}
      >
        <code
          id="outPut"
          style={{
            whiteSpace: "pre-wrap",
            color: "white",
            overflowWrap: "break-word",
          }}
        >
          $ python main.py <br />
          Hello World !!
        </code>
      </div>
    </>
  );
}
